name: Publish to PyPi
on:
  workflow_dispatch:
  push:
    paths:
      - "setup.py"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build backup
    steps:
    - name: Install dependencies
      run: pip install wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}